--
-- registry.lua
-- csv2lua
--
-- Created by Carl on 05/20/15.
-- Copyright (c) 2015 Carl. All rights reserved.
--

local registry = {
	["team_3v3_born_point_x_blue"] = {
		["type"] = 0,
		["id"] = "team_3v3_born_point_x_blue",
		["value"] = 4400,
		["group"] = "",
		["desc"] = "3v3蓝方复活点y",
	},
	["inBattleDialog.114"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.114",
		["value"] = "吾家三世公侯，岂识汝山野匹夫",
		["group"] = "",
		["desc"] = "",
	},
	["team_3v3_drop_item_force_up_point_x_red"] = {
		["type"] = 0,
		["id"] = "team_3v3_drop_item_force_up_point_x_red",
		["value"] = 1300,
		["group"] = "",
		["desc"] = "3v3红方掉落Force道具出生点x",
	},
	["test.num"] = {
		["type"] = 0,
		["id"] = "test.num",
		["value"] = 123,
		["group"] = "",
		["desc"] = "",
	},
	["dashDungeon.bossMonGroup"] = {
		["type"] = 3,
		["id"] = "dashDungeon.bossMonGroup",
		["value"] = {
			[1] = 1001,
			[2] = 1002,
			[3] = 1003,
		},
		["group"] = "",
		["desc"] = "跑酷副本boss阶段小怪配置",
	},
	["storyBossDialogs.101"] = {
		["type"] = 1,
		["id"] = "storyBossDialogs.101",
		["value"] = "快上！给我往死里打！#大汉气数已尽！#不行，看来还由本军师来把关！",
		["group"] = "",
		["desc"] = "背景boss对话",
	},
	["heartbeat_interval"] = {
		["type"] = 0,
		["id"] = "heartbeat_interval",
		["value"] = 20,
		["group"] = "",
		["desc"] = "发送心跳间隔时间",
	},
	["team_3v3_born_point_x_red"] = {
		["type"] = 0,
		["id"] = "team_3v3_born_point_x_red",
		["value"] = 450,
		["group"] = "",
		["desc"] = "3v3红方复活点x",
	},
	["team_3v3_drop_item_hp_up_point_x_blue"] = {
		["type"] = 0,
		["id"] = "team_3v3_drop_item_hp_up_point_x_blue",
		["value"] = 3500,
		["group"] = "",
		["desc"] = "3v3蓝方掉落HP道具出生点x",
	},
	["inBattleDialog.115"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.115",
		["value"] = "无知小儿,安敢如此!",
		["group"] = "",
		["desc"] = "",
	},
	["inBattleDialog.104"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.104",
		["value"] = "方向感略差(⊙_⊙)？",
		["group"] = "",
		["desc"] = "",
	},
	["sign_in.day2"] = {
		["type"] = 2,
		["id"] = "sign_in.day2",
		["value"] = {
			[1] = {
				[1] = 3,
				[2] = 1,
				[3] = 85100205,
			},
		},
		["group"] = "",
		["desc"] = "",
	},
	["atkGuideConf.102"] = {
		["type"] = 3,
		["id"] = "atkGuideConf.102",
		["value"] = {
			[1] = 0,
			[2] = 203,
			[3] = 1,
			[4] = """靠近按普攻可拾取炸弹""",
		},
		["group"] = "",
		["desc"] = "炸弹引导",
	},
	["inBattleDialog.109"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.109",
		["value"] = "老衲……尊老……",
		["group"] = "",
		["desc"] = "",
	},
	["inBattleDialog.117"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.117",
		["value"] = "哪里窜出来的混账东西,坏老夫雅致!",
		["group"] = "",
		["desc"] = "",
	},
	["inBattleDialog.105"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.105",
		["value"] = "黄巾贼可怕，见人就杀。",
		["group"] = "",
		["desc"] = "",
	},
	["team_3v3_drop_item_force_up_point_x_blue"] = {
		["type"] = 0,
		["id"] = "team_3v3_drop_item_force_up_point_x_blue",
		["value"] = 3700,
		["group"] = "",
		["desc"] = "3v3蓝方掉落Force道具出生点x",
	},
	["inBattleDialog.118"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.118",
		["value"] = "逮住女娃一枚，先驯服再……",
		["group"] = "",
		["desc"] = "",
	},
	["arena.admire_reward"] = {
		["type"] = 2,
		["id"] = "arena.admire_reward",
		["value"] = {
			[1] = {
				[1] = 8,
				[2] = 20,
				[3] = 0,
			},
		},
		["group"] = "",
		["desc"] = "竞技场膜拜奖励",
	},
	["sign_in.day6"] = {
		["type"] = 2,
		["id"] = "sign_in.day6",
		["value"] = {
			[1] = {
				[1] = 3,
				[2] = 10,
				[3] = 91210001,
			},
		},
		["group"] = "",
		["desc"] = "",
	},
	["battleConf.totalRefloatLimPVE"] = {
		["type"] = 0,
		["id"] = "battleConf.totalRefloatLimPVE",
		["value"] = 60,
		["group"] = "",
		["desc"] = "玩家对怪物(pve)的续飞上限",
	},
	["inBattleDialog.119"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.119",
		["value"] = "行刺事泄，定是愚民告密！",
		["group"] = "",
		["desc"] = "",
	},
	["atkGuideConf.104"] = {
		["type"] = 3,
		["id"] = "atkGuideConf.104",
		["value"] = {
			[1] = 0,
			[2] = 203,
			[3] = 1,
			[4] = """靠近按普攻可拾取火把""",
		},
		["group"] = "",
		["desc"] = "火把引导",
	},
	["heartbeat_timeout"] = {
		["type"] = 0,
		["id"] = "heartbeat_timeout",
		["value"] = 60,
		["group"] = "",
		["desc"] = "心跳超时时间",
	},
	["inBattleDialog.110"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.110",
		["value"] = "真心伤不起。",
		["group"] = "",
		["desc"] = "",
	},
	["inBattleDialog.102"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.102",
		["value"] = "英雄救我！",
		["group"] = "",
		["desc"] = "",
	},
	["sign_in.day5"] = {
		["type"] = 2,
		["id"] = "sign_in.day5",
		["value"] = {
			[1] = {
				[1] = 10,
				[2] = 5,
				[3] = 0,
			},
		},
		["group"] = "",
		["desc"] = "",
	},
	["inBattleDialog.103"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.103",
		["value"] = "混账！",
		["group"] = "",
		["desc"] = "",
	},
	["sign_in.days_7"] = {
		["type"] = 2,
		["id"] = "sign_in.days_7",
		["value"] = {
			[1] = {
				[1] = 1,
				[2] = 30,
				[3] = 0,
			},
			[2] = {
				[1] = 3,
				[2] = 1,
				[3] = 85201003,
			},
			[3] = {
				[1] = 3,
				[2] = 10,
				[3] = 91170001,
			},
		},
		["group"] = "",
		["desc"] = "",
	},
	["inBattleDialog.107"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.107",
		["value"] = "想不到还活着，快点逃！",
		["group"] = "",
		["desc"] = "",
	},
	["inBattleDialog.116"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.116",
		["value"] = "疯了，不分敌我。",
		["group"] = "",
		["desc"] = "",
	},
	["test.string"] = {
		["type"] = 1,
		["id"] = "test.string",
		["value"] = "foxyu",
		["group"] = "",
		["desc"] = "",
	},
	["inBattleDialog.501"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.501",
		["value"] = "我%s前来助你一臂之力#%s在此，谁来受死。",
		["group"] = "",
		["desc"] = "助战NPC出场气泡文字",
	},
	["inBattleDialog.134"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.134",
		["value"] = "关羽在此,尔等受死。",
		["group"] = "",
		["desc"] = "",
	},
	["atkGuideConf.105"] = {
		["type"] = 3,
		["id"] = "atkGuideConf.105",
		["value"] = {
			[1] = 104,
			[2] = 203,
			[3] = 2,
			[4] = """投掷到粮仓中""",
		},
		["group"] = "",
		["desc"] = "火把投掷引导",
	},
	["inBattleDialog.130"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.130",
		["value"] = "你是哪个营房的？",
		["group"] = "",
		["desc"] = "",
	},
	["inBattleDialog.112"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.112",
		["value"] = "无耻老贼！",
		["group"] = "",
		["desc"] = "",
	},
	["arena.admired_thousand_reward"] = {
		["type"] = 2,
		["id"] = "arena.admired_thousand_reward",
		["value"] = {
			[1] = {
				[1] = 8,
				[2] = 100,
				[3] = 0,
			},
		},
		["group"] = "",
		["desc"] = "竞技场被膜拜每1000次奖励",
	},
	["sign_in.days_5"] = {
		["type"] = 2,
		["id"] = "sign_in.days_5",
		["value"] = {
			[1] = {
				[1] = 1,
				[2] = 20,
				[3] = 0,
			},
			[2] = {
				[1] = 3,
				[2] = 10,
				[3] = 91130001,
			},
			[3] = {
				[1] = 3,
				[2] = 10,
				[3] = 91210001,
			},
		},
		["group"] = "",
		["desc"] = "",
	},
	["battleConf.ObjContinuousBeAtkLim"] = {
		["type"] = 0,
		["id"] = "battleConf.ObjContinuousBeAtkLim",
		["value"] = 8,
		["group"] = "",
		["desc"] = "连续播放N次受击动作，过程中没有浮空或倒地，则下次受到伤害时，会被打倒在地。",
	},
	["battleConf.totalRefloatLimQiecuo"] = {
		["type"] = 0,
		["id"] = "battleConf.totalRefloatLimQiecuo",
		["value"] = 30,
		["group"] = "",
		["desc"] = "切磋的续飞上限",
	},
	["inBattleDialog.129"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.129",
		["value"] = "酒坛里有火把！",
		["group"] = "",
		["desc"] = "",
	},
	["inBattleDialog.135"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.135",
		["value"] = "燕人张翼德在此，哪个王八活得不耐烦了？",
		["group"] = "",
		["desc"] = "",
	},
	["storyBossDialogs.103"] = {
		["type"] = 1,
		["id"] = "storyBossDialogs.103",
		["value"] = "看到这家伙，脸上隐约有滚烫的感觉……#我就摸摸长须，不说话。",
		["group"] = "",
		["desc"] = "",
	},
	["storyBossDialogs.102"] = {
		["type"] = 1,
		["id"] = "storyBossDialogs.102",
		["value"] = "哟呵！哟呵！这家伙真心不赖！#你看！你看！大哥快招架不住了！哈哈，笑死俺了。#二哥，你又脸红了！",
		["group"] = "",
		["desc"] = "",
	},
	["atkGuideConf.103"] = {
		["type"] = 3,
		["id"] = "atkGuideConf.103",
		["value"] = {
			[1] = 0,
			[2] = 203,
			[3] = 1,
			[4] = """击破酒坛可掉落火把""",
		},
		["group"] = "",
		["desc"] = "酒坛引导2",
	},
	["team_3v3_drop_item_hp_up_point_x_red"] = {
		["type"] = 0,
		["id"] = "team_3v3_drop_item_hp_up_point_x_red",
		["value"] = 1100,
		["group"] = "",
		["desc"] = "3v3红方掉落HP道具出生点x",
	},
	["atkGuideConf.101"] = {
		["type"] = 3,
		["id"] = "atkGuideConf.101",
		["value"] = {
			[1] = 0,
			[2] = 203,
			[3] = 1,
			[4] = """击破酒坛可掉落炸弹""",
		},
		["group"] = "",
		["desc"] = "酒坛引导1",
	},
	["inBattleDialog.136"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.136",
		["value"] = "得民心者得天下！",
		["group"] = "",
		["desc"] = "",
	},
	["battleConf.totalRefloatLimPVP"] = {
		["type"] = 0,
		["id"] = "battleConf.totalRefloatLimPVP",
		["value"] = 30,
		["group"] = "",
		["desc"] = "玩家对玩家(pvp)的续飞上限",
	},
	["auto_battle_open_lv"] = {
		["type"] = 0,
		["id"] = "auto_battle_open_lv",
		["value"] = 17,
		["group"] = "",
		["desc"] = "自动战斗开启等级",
	},
	["sign_in.day7"] = {
		["type"] = 2,
		["id"] = "sign_in.day7",
		["value"] = {
			[1] = {
				[1] = 3,
				[2] = 1,
				[3] = 85200111,
			},
		},
		["group"] = "",
		["desc"] = "",
	},
	["inBattleDialog.133"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.133",
		["value"] = "竟敢在我面前舞大刀？",
		["group"] = "",
		["desc"] = "",
	},
	["inBattleDialog.132"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.132",
		["value"] = "我宁愿当一个，能够实现自己抱负的奸雄。",
		["group"] = "",
		["desc"] = "",
	},
	["inBattleDialog.106"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.106",
		["value"] = "黄巾之乱，何时平定？",
		["group"] = "",
		["desc"] = "",
	},
	["inBattleDialog.131"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.131",
		["value"] = "誓死保护主公！",
		["group"] = "",
		["desc"] = "",
	},
	["inBattleDialog.111"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.111",
		["value"] = "生啖你肉！安敢在此饶舌？",
		["group"] = "",
		["desc"] = "",
	},
	["sign_in.day1"] = {
		["type"] = 2,
		["id"] = "sign_in.day1",
		["value"] = {
			[1] = {
				[1] = 2,
				[2] = 100000,
				[3] = 0,
			},
		},
		["group"] = "",
		["desc"] = "",
	},
	["sign_in.day3"] = {
		["type"] = 2,
		["id"] = "sign_in.day3",
		["value"] = {
			[1] = {
				[1] = 5,
				[2] = 5000,
				[3] = 0,
			},
		},
		["group"] = "",
		["desc"] = "",
	},
	["inBattleDialog.101"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.101",
		["value"] = "看这会还谁能救你。",
		["group"] = "",
		["desc"] = "",
	},
	["inBattleDialog.121"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.121",
		["value"] = "有罪没罪，都得认罪！",
		["group"] = "",
		["desc"] = "",
	},
	["inBattleDialog.128"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.128",
		["value"] = "敌人来袭，粮仓不保，赶紧弃甲归田。",
		["group"] = "",
		["desc"] = "",
	},
	["inBattleDialog.127"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.127",
		["value"] = "来来来，三碗烧酒下肚，划拳比武齐助兴！",
		["group"] = "",
		["desc"] = "",
	},
	["inBattleDialog.122"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.122",
		["value"] = "尼玛，真不要脸！",
		["group"] = "",
		["desc"] = "",
	},
	["sign_in.day4"] = {
		["type"] = 2,
		["id"] = "sign_in.day4",
		["value"] = {
			[1] = {
				[1] = 3,
				[2] = 5,
				[3] = 91130001,
			},
		},
		["group"] = "",
		["desc"] = "",
	},
	["inBattleDialog.123"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.123",
		["value"] = "快！大家一起上。",
		["group"] = "",
		["desc"] = "",
	},
	["battleConf.MonsterAIHoverRange"] = {
		["type"] = 3,
		["id"] = "battleConf.MonsterAIHoverRange",
		["value"] = {
			[1] = 400,
			[2] = 250,
		},
		["group"] = "",
		["desc"] = "怪物AI在跟踪敌人到攻击盒子内以后未能攻击的情况下在主角周围随机移动的范围",
	},
	["dailytask.task_reward"] = {
		["type"] = 1,
		["id"] = "dailytask.task_reward",
		["value"] = {
			[1] = {
				[1] = 2,
				[2] = "1200*(PlayerLv-15)*(0.4+0.2*Quality)",
				[3] = 0,
			},
			[2] = {
				[1] = 5,
				[2] = "10*PlayerLv*(0.4+0.2*Quality)",
				[3] = 0,
			},
			[3] = {
				[1] = 6,
				[2] = "100*PlayerLv*(0.4+0.2*Quality)",
				[3] = 0,
			},
		},
		["group"] = "",
		["desc"] = "日常任务单个任务的奖励",
	},
	["parkour.reviveTimeout"] = {
		["type"] = 0,
		["id"] = "parkour.reviveTimeout",
		["value"] = 5,
		["group"] = "",
		["desc"] = "跑酷玩法复活倒计时",
	},
	["remote_walk_threshold_x"] = {
		["type"] = 3,
		["id"] = "remote_walk_threshold_x",
		["value"] = 200,
		["group"] = "",
		["desc"] = "X轴位置同步参数",
	},
	["inBattleDialog.126"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.126",
		["value"] = "放开她，等我来！",
		["group"] = "",
		["desc"] = "",
	},
	["inBattleDialog.125"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.125",
		["value"] = "乱世现英雄，回家烧香还神。",
		["group"] = "",
		["desc"] = "",
	},
	["inBattleDialog.120"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.120",
		["value"] = "救我！",
		["group"] = "",
		["desc"] = "",
	},
	["inBattleDialog.124"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.124",
		["value"] = "欲加之罪，何患无辞？",
		["group"] = "",
		["desc"] = "",
	},
	["remote_walk_threshold_y"] = {
		["type"] = 3,
		["id"] = "remote_walk_threshold_y",
		["value"] = 100,
		["group"] = "",
		["desc"] = "Y轴位置同步参数",
	},
	["inBattleDialog.113"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.113",
		["value"] = "饭囊、酒桶、肉袋!",
		["group"] = "",
		["desc"] = "",
	},
	["inBattleDialog.108"] = {
		["type"] = 1,
		["id"] = "inBattleDialog.108",
		["value"] = "连小孩也不放过。",
		["group"] = "",
		["desc"] = "",
	},
	["sign_in.days_3"] = {
		["type"] = 2,
		["id"] = "sign_in.days_3",
		["value"] = {
			[1] = {
				[1] = 1,
				[2] = 10,
				[3] = 0,
			},
			[2] = {
				[1] = 2,
				[2] = 100000,
				[3] = 0,
			},
		},
		["group"] = "",
		["desc"] = "",
	},
}

return registry

